[package]
name = "z2e2"
version = "1.99.0"
authors = ["Chris Frantz <frantzcj@gmail.com>"]
edition = "2018"
build = "build.rs"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
# Basic application stuff
built = "0.4.4"
chrono = "0.4"
structopt = "0.3.18"
log = "0.4"
env_logger = "0.8.3"
directories = "3.0.1"
error-chain = "0.12.4"
rand = "0.8.0"
rustyline = "6.3.0"
libc = "0.2"
once_cell = "1.4.1"
pathdiff = "0.2.0"
whoami = "0.9.0"
shellwords = "1.1.0"
smart-default = "0.6.0"
sha2 = "0.9.2"
termcolor = "1.1"
indexmap = {version="1.6.1", features=["serde"]}
num_enum = "0.5.4"

# Python integration stuff
pyo3 = {version="0.13.0", path="third_party/pyo3", features=["indexmap"]}
dict_derive = "0.3.0"

# Serialization stuff
ron = "*"
serde = { version="1", features=["serde_derive", "rc"] }
typetag = "0.1"
serde_json = "1.0.59"

# Gui stuff
sdl2 = "0.34"
gl = "0.14.0"
nfd = "0.0.4"
#imgui = "0.5.0"
imgui = {version="*", path="third_party/imgui-rs/imgui" }
imgui-opengl-renderer = {version="*", path="third_party/rust-imgui-opengl-renderer" }
imgui-sdl2 = {version="*", path="third_party/rust-imgui-sdl2" }

[target.'cfg(unix)'.dependencies]
nix = "0.18"

[build-dependencies]
built = {version="0.4.4", features=["git2"]}
