package(default_visibility = ["//visibility:public"])

filegroup(
  name = 'addr2line',
  srcs = [
    '@mingw_compiler_win64//:addr2line',
    'x86_64-w64-mingw32.shared-addr2line',
  ],
)

filegroup(
  name = 'ar',
  srcs = [
    '@mingw_compiler_win64//:ar',
    'x86_64-w64-mingw32.shared-ar',
  ],
)

filegroup(
  name = 'as',
  srcs = [
    '@mingw_compiler_win64//:as',
    'x86_64-w64-mingw32.shared-as',
  ],
)

filegroup(
  name = 'c++filt',
  srcs = [
    '@mingw_compiler_win64//:c++filt',
    'x86_64-w64-mingw32.shared-c++filt',
  ],
)

filegroup(
  name = 'dlltool',
  srcs = [
    '@mingw_compiler_win64//:dlltool',
    'x86_64-w64-mingw32.shared-dlltool',
  ],
)

filegroup(
  name = 'dllwrap',
  srcs = [
    '@mingw_compiler_win64//:dllwrap',
    'x86_64-w64-mingw32.shared-dllwrap',
  ],
)

filegroup(
  name = 'elfedit',
  srcs = [
    '@mingw_compiler_win64//:elfedit',
    'x86_64-w64-mingw32.shared-elfedit',
  ],
)

filegroup(
  name = 'gprof',
  srcs = [
    '@mingw_compiler_win64//:gprof',
    'x86_64-w64-mingw32.shared-gprof',
  ],
)

filegroup(
  name = 'ld',
  srcs = [
    '@mingw_compiler_win64//:ld',
    'x86_64-w64-mingw32.shared-ld',
  ],
)

filegroup(
  name = 'ld.bfd',
  srcs = [
    '@mingw_compiler_win64//:ld.bfd',
    'x86_64-w64-mingw32.shared-ld.bfd',
  ],
)

filegroup(
  name = 'nm',
  srcs = [
    '@mingw_compiler_win64//:nm',
    'x86_64-w64-mingw32.shared-nm',
  ],
)

filegroup(
  name = 'objcopy',
  srcs = [
    '@mingw_compiler_win64//:objcopy',
    'x86_64-w64-mingw32.shared-objcopy',
  ],
)

filegroup(
  name = 'objdump',
  srcs = [
    '@mingw_compiler_win64//:objdump',
    'x86_64-w64-mingw32.shared-objdump',
  ],
)

filegroup(
  name = 'ranlib',
  srcs = [
    '@mingw_compiler_win64//:ranlib',
    'x86_64-w64-mingw32.shared-ranlib',
  ],
)

filegroup(
  name = 'readelf',
  srcs = [
    '@mingw_compiler_win64//:readelf',
    'x86_64-w64-mingw32.shared-readelf',
  ],
)

filegroup(
  name = 'size',
  srcs = [
    '@mingw_compiler_win64//:size',
    'x86_64-w64-mingw32.shared-size',
  ],
)

filegroup(
  name = 'strings',
  srcs = [
    '@mingw_compiler_win64//:strings',
    'x86_64-w64-mingw32.shared-strings',
  ],
)

filegroup(
  name = 'strip',
  srcs = [
    '@mingw_compiler_win64//:strip',
    'x86_64-w64-mingw32.shared-strip',
  ],
)

filegroup(
  name = 'windmc',
  srcs = [
    '@mingw_compiler_win64//:windmc',
    'x86_64-w64-mingw32.shared-windmc',
  ],
)

filegroup(
  name = 'windres',
  srcs = [
    '@mingw_compiler_win64//:windres',
    'x86_64-w64-mingw32.shared-windres',
  ],
)

filegroup(
  name = 'gcc',
  srcs = [
    '@mingw_compiler_win64//:gcc',
    'x86_64-w64-mingw32.shared-gcc',
  ],
)

filegroup(
    name = 'tool-wrappers',
    srcs = [
        ':addr2line',
        ':ar',
        ':as',
        ':c++filt',
        ':dlltool',
        ':dllwrap',
        ':elfedit',
        ':gcc',
        ':gprof',
        ':ld',
        ':ld.bfd',
        ':nm',
        ':objcopy',
        ':objdump',
        ':ranlib',
        ':readelf',
        ':size',
        ':strings',
        ':strip',
        ':windmc',
        ':windres',
    ],
)
