[package]
name = "python_gui"
version = "0.1.0"
edition = "2021"

[dependencies]
pyo3 = { version="0.23.3", features=["anyhow"]}
imgui-sys = {workspace = true, features=["docking"]}
imgui = { workspace = true, features = ["docking", "tables-api"] }
imgui-sdl2-support = { version = "0.13.0", git="https://github.com/imgui-rs/imgui-sdl2-support"}
imgui-glow-renderer = { version = "0.13.0" }
anyhow = { version = "1.0", features = ["backtrace"] }
glow = "0"
image = "0.23"
sdl2 = "0.37"
winit = { version = "0.29.3" }
send_wrapper = "0.6.0"

[build-dependencies]
cc = "1.0"
