[package]
name = "z2edit"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[lib]
name = "_z2edit"
crate-type = ["cdylib"]

[dependencies]
python_gui = { path = "../python_gui" }
imgui = { workspace = true, features = ["docking", "tables-api"] }
pyo3 = { version="0.23.3", features=["anyhow"]}
anyhow = { version = "1.0", features = ["backtrace"] }
thiserror = "2.0.9"
serde = { version = "1.0.217", features = ["derive"] }
