package(default_visibility=["//visibility:public"])

## proto_library(
##     name = "rominfo_proto",
##     srcs = [
##         "rominfo.proto",
##         "keybinds.proto",
##     ],
## )
## 
## cc_proto_library(
##     name = "rominfo",
##     deps = [":rominfo_proto"],
## )
