/* automatically generated by rust-bindgen 0.68.1 */
#![allow(dead_code)]
#![allow(non_snake_case)]
#![allow(non_camel_case_types)]

#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct __OPLL_PATCH {
    pub TL: u32,
    pub FB: u32,
    pub EG: u32,
    pub ML: u32,
    pub AR: u32,
    pub DR: u32,
    pub SL: u32,
    pub RR: u32,
    pub KR: u32,
    pub KL: u32,
    pub AM: u32,
    pub PM: u32,
    pub WS: u32,
}
#[test]
fn bindgen_test_layout___OPLL_PATCH() {
    const UNINIT: ::std::mem::MaybeUninit<__OPLL_PATCH> = ::std::mem::MaybeUninit::uninit();
    let ptr = UNINIT.as_ptr();
    assert_eq!(
        ::std::mem::size_of::<__OPLL_PATCH>(),
        52usize,
        concat!("Size of: ", stringify!(__OPLL_PATCH))
    );
    assert_eq!(
        ::std::mem::align_of::<__OPLL_PATCH>(),
        4usize,
        concat!("Alignment of ", stringify!(__OPLL_PATCH))
    );
    assert_eq!(
        unsafe { ::std::ptr::addr_of!((*ptr).TL) as usize - ptr as usize },
        0usize,
        concat!(
            "Offset of field: ",
            stringify!(__OPLL_PATCH),
            "::",
            stringify!(TL)
        )
    );
    assert_eq!(
        unsafe { ::std::ptr::addr_of!((*ptr).FB) as usize - ptr as usize },
        4usize,
        concat!(
            "Offset of field: ",
            stringify!(__OPLL_PATCH),
            "::",
            stringify!(FB)
        )
    );
    assert_eq!(
        unsafe { ::std::ptr::addr_of!((*ptr).EG) as usize - ptr as usize },
        8usize,
        concat!(
            "Offset of field: ",
            stringify!(__OPLL_PATCH),
            "::",
            stringify!(EG)
        )
    );
    assert_eq!(
        unsafe { ::std::ptr::addr_of!((*ptr).ML) as usize - ptr as usize },
        12usize,
        concat!(
            "Offset of field: ",
            stringify!(__OPLL_PATCH),
            "::",
            stringify!(ML)
        )
    );
    assert_eq!(
        unsafe { ::std::ptr::addr_of!((*ptr).AR) as usize - ptr as usize },
        16usize,
        concat!(
            "Offset of field: ",
            stringify!(__OPLL_PATCH),
            "::",
            stringify!(AR)
        )
    );
    assert_eq!(
        unsafe { ::std::ptr::addr_of!((*ptr).DR) as usize - ptr as usize },
        20usize,
        concat!(
            "Offset of field: ",
            stringify!(__OPLL_PATCH),
            "::",
            stringify!(DR)
        )
    );
    assert_eq!(
        unsafe { ::std::ptr::addr_of!((*ptr).SL) as usize - ptr as usize },
        24usize,
        concat!(
            "Offset of field: ",
            stringify!(__OPLL_PATCH),
            "::",
            stringify!(SL)
        )
    );
    assert_eq!(
        unsafe { ::std::ptr::addr_of!((*ptr).RR) as usize - ptr as usize },
        28usize,
        concat!(
            "Offset of field: ",
            stringify!(__OPLL_PATCH),
            "::",
            stringify!(RR)
        )
    );
    assert_eq!(
        unsafe { ::std::ptr::addr_of!((*ptr).KR) as usize - ptr as usize },
        32usize,
        concat!(
            "Offset of field: ",
            stringify!(__OPLL_PATCH),
            "::",
            stringify!(KR)
        )
    );
    assert_eq!(
        unsafe { ::std::ptr::addr_of!((*ptr).KL) as usize - ptr as usize },
        36usize,
        concat!(
            "Offset of field: ",
            stringify!(__OPLL_PATCH),
            "::",
            stringify!(KL)
        )
    );
    assert_eq!(
        unsafe { ::std::ptr::addr_of!((*ptr).AM) as usize - ptr as usize },
        40usize,
        concat!(
            "Offset of field: ",
            stringify!(__OPLL_PATCH),
            "::",
            stringify!(AM)
        )
    );
    assert_eq!(
        unsafe { ::std::ptr::addr_of!((*ptr).PM) as usize - ptr as usize },
        44usize,
        concat!(
            "Offset of field: ",
            stringify!(__OPLL_PATCH),
            "::",
            stringify!(PM)
        )
    );
    assert_eq!(
        unsafe { ::std::ptr::addr_of!((*ptr).WS) as usize - ptr as usize },
        48usize,
        concat!(
            "Offset of field: ",
            stringify!(__OPLL_PATCH),
            "::",
            stringify!(WS)
        )
    );
}
pub type OPLL_PATCH = __OPLL_PATCH;
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct __OPLL_SLOT {
    pub number: u8,
    pub type_: u8,
    pub patch: *mut OPLL_PATCH,
    pub output: [i32; 2usize],
    pub wave_table: *mut u16,
    pub pg_phase: u32,
    pub pg_out: u32,
    pub pg_keep: u8,
    pub blk_fnum: u16,
    pub fnum: u16,
    pub blk: u8,
    pub eg_state: u8,
    pub volume: i32,
    pub key_flag: u8,
    pub sus_flag: u8,
    pub tll: u16,
    pub rks: u8,
    pub eg_rate_h: u8,
    pub eg_rate_l: u8,
    pub eg_shift: u32,
    pub eg_out: u32,
    pub update_requests: u32,
}
#[test]
fn bindgen_test_layout___OPLL_SLOT() {
    const UNINIT: ::std::mem::MaybeUninit<__OPLL_SLOT> = ::std::mem::MaybeUninit::uninit();
    let ptr = UNINIT.as_ptr();
    assert_eq!(
        ::std::mem::size_of::<__OPLL_SLOT>(),
        72usize,
        concat!("Size of: ", stringify!(__OPLL_SLOT))
    );
    assert_eq!(
        ::std::mem::align_of::<__OPLL_SLOT>(),
        8usize,
        concat!("Alignment of ", stringify!(__OPLL_SLOT))
    );
    assert_eq!(
        unsafe { ::std::ptr::addr_of!((*ptr).number) as usize - ptr as usize },
        0usize,
        concat!(
            "Offset of field: ",
            stringify!(__OPLL_SLOT),
            "::",
            stringify!(number)
        )
    );
    assert_eq!(
        unsafe { ::std::ptr::addr_of!((*ptr).type_) as usize - ptr as usize },
        1usize,
        concat!(
            "Offset of field: ",
            stringify!(__OPLL_SLOT),
            "::",
            stringify!(type_)
        )
    );
    assert_eq!(
        unsafe { ::std::ptr::addr_of!((*ptr).patch) as usize - ptr as usize },
        8usize,
        concat!(
            "Offset of field: ",
            stringify!(__OPLL_SLOT),
            "::",
            stringify!(patch)
        )
    );
    assert_eq!(
        unsafe { ::std::ptr::addr_of!((*ptr).output) as usize - ptr as usize },
        16usize,
        concat!(
            "Offset of field: ",
            stringify!(__OPLL_SLOT),
            "::",
            stringify!(output)
        )
    );
    assert_eq!(
        unsafe { ::std::ptr::addr_of!((*ptr).wave_table) as usize - ptr as usize },
        24usize,
        concat!(
            "Offset of field: ",
            stringify!(__OPLL_SLOT),
            "::",
            stringify!(wave_table)
        )
    );
    assert_eq!(
        unsafe { ::std::ptr::addr_of!((*ptr).pg_phase) as usize - ptr as usize },
        32usize,
        concat!(
            "Offset of field: ",
            stringify!(__OPLL_SLOT),
            "::",
            stringify!(pg_phase)
        )
    );
    assert_eq!(
        unsafe { ::std::ptr::addr_of!((*ptr).pg_out) as usize - ptr as usize },
        36usize,
        concat!(
            "Offset of field: ",
            stringify!(__OPLL_SLOT),
            "::",
            stringify!(pg_out)
        )
    );
    assert_eq!(
        unsafe { ::std::ptr::addr_of!((*ptr).pg_keep) as usize - ptr as usize },
        40usize,
        concat!(
            "Offset of field: ",
            stringify!(__OPLL_SLOT),
            "::",
            stringify!(pg_keep)
        )
    );
    assert_eq!(
        unsafe { ::std::ptr::addr_of!((*ptr).blk_fnum) as usize - ptr as usize },
        42usize,
        concat!(
            "Offset of field: ",
            stringify!(__OPLL_SLOT),
            "::",
            stringify!(blk_fnum)
        )
    );
    assert_eq!(
        unsafe { ::std::ptr::addr_of!((*ptr).fnum) as usize - ptr as usize },
        44usize,
        concat!(
            "Offset of field: ",
            stringify!(__OPLL_SLOT),
            "::",
            stringify!(fnum)
        )
    );
    assert_eq!(
        unsafe { ::std::ptr::addr_of!((*ptr).blk) as usize - ptr as usize },
        46usize,
        concat!(
            "Offset of field: ",
            stringify!(__OPLL_SLOT),
            "::",
            stringify!(blk)
        )
    );
    assert_eq!(
        unsafe { ::std::ptr::addr_of!((*ptr).eg_state) as usize - ptr as usize },
        47usize,
        concat!(
            "Offset of field: ",
            stringify!(__OPLL_SLOT),
            "::",
            stringify!(eg_state)
        )
    );
    assert_eq!(
        unsafe { ::std::ptr::addr_of!((*ptr).volume) as usize - ptr as usize },
        48usize,
        concat!(
            "Offset of field: ",
            stringify!(__OPLL_SLOT),
            "::",
            stringify!(volume)
        )
    );
    assert_eq!(
        unsafe { ::std::ptr::addr_of!((*ptr).key_flag) as usize - ptr as usize },
        52usize,
        concat!(
            "Offset of field: ",
            stringify!(__OPLL_SLOT),
            "::",
            stringify!(key_flag)
        )
    );
    assert_eq!(
        unsafe { ::std::ptr::addr_of!((*ptr).sus_flag) as usize - ptr as usize },
        53usize,
        concat!(
            "Offset of field: ",
            stringify!(__OPLL_SLOT),
            "::",
            stringify!(sus_flag)
        )
    );
    assert_eq!(
        unsafe { ::std::ptr::addr_of!((*ptr).tll) as usize - ptr as usize },
        54usize,
        concat!(
            "Offset of field: ",
            stringify!(__OPLL_SLOT),
            "::",
            stringify!(tll)
        )
    );
    assert_eq!(
        unsafe { ::std::ptr::addr_of!((*ptr).rks) as usize - ptr as usize },
        56usize,
        concat!(
            "Offset of field: ",
            stringify!(__OPLL_SLOT),
            "::",
            stringify!(rks)
        )
    );
    assert_eq!(
        unsafe { ::std::ptr::addr_of!((*ptr).eg_rate_h) as usize - ptr as usize },
        57usize,
        concat!(
            "Offset of field: ",
            stringify!(__OPLL_SLOT),
            "::",
            stringify!(eg_rate_h)
        )
    );
    assert_eq!(
        unsafe { ::std::ptr::addr_of!((*ptr).eg_rate_l) as usize - ptr as usize },
        58usize,
        concat!(
            "Offset of field: ",
            stringify!(__OPLL_SLOT),
            "::",
            stringify!(eg_rate_l)
        )
    );
    assert_eq!(
        unsafe { ::std::ptr::addr_of!((*ptr).eg_shift) as usize - ptr as usize },
        60usize,
        concat!(
            "Offset of field: ",
            stringify!(__OPLL_SLOT),
            "::",
            stringify!(eg_shift)
        )
    );
    assert_eq!(
        unsafe { ::std::ptr::addr_of!((*ptr).eg_out) as usize - ptr as usize },
        64usize,
        concat!(
            "Offset of field: ",
            stringify!(__OPLL_SLOT),
            "::",
            stringify!(eg_out)
        )
    );
    assert_eq!(
        unsafe { ::std::ptr::addr_of!((*ptr).update_requests) as usize - ptr as usize },
        68usize,
        concat!(
            "Offset of field: ",
            stringify!(__OPLL_SLOT),
            "::",
            stringify!(update_requests)
        )
    );
}
pub type OPLL_SLOT = __OPLL_SLOT;
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct __OPLL_RateConv {
    pub ch: ::std::os::raw::c_int,
    pub timer: f64,
    pub f_ratio: f64,
    pub sinc_table: *mut i16,
    pub buf: *mut *mut i16,
}
#[test]
fn bindgen_test_layout___OPLL_RateConv() {
    const UNINIT: ::std::mem::MaybeUninit<__OPLL_RateConv> = ::std::mem::MaybeUninit::uninit();
    let ptr = UNINIT.as_ptr();
    assert_eq!(
        ::std::mem::size_of::<__OPLL_RateConv>(),
        40usize,
        concat!("Size of: ", stringify!(__OPLL_RateConv))
    );
    assert_eq!(
        ::std::mem::align_of::<__OPLL_RateConv>(),
        8usize,
        concat!("Alignment of ", stringify!(__OPLL_RateConv))
    );
    assert_eq!(
        unsafe { ::std::ptr::addr_of!((*ptr).ch) as usize - ptr as usize },
        0usize,
        concat!(
            "Offset of field: ",
            stringify!(__OPLL_RateConv),
            "::",
            stringify!(ch)
        )
    );
    assert_eq!(
        unsafe { ::std::ptr::addr_of!((*ptr).timer) as usize - ptr as usize },
        8usize,
        concat!(
            "Offset of field: ",
            stringify!(__OPLL_RateConv),
            "::",
            stringify!(timer)
        )
    );
    assert_eq!(
        unsafe { ::std::ptr::addr_of!((*ptr).f_ratio) as usize - ptr as usize },
        16usize,
        concat!(
            "Offset of field: ",
            stringify!(__OPLL_RateConv),
            "::",
            stringify!(f_ratio)
        )
    );
    assert_eq!(
        unsafe { ::std::ptr::addr_of!((*ptr).sinc_table) as usize - ptr as usize },
        24usize,
        concat!(
            "Offset of field: ",
            stringify!(__OPLL_RateConv),
            "::",
            stringify!(sinc_table)
        )
    );
    assert_eq!(
        unsafe { ::std::ptr::addr_of!((*ptr).buf) as usize - ptr as usize },
        32usize,
        concat!(
            "Offset of field: ",
            stringify!(__OPLL_RateConv),
            "::",
            stringify!(buf)
        )
    );
}
pub type OPLL_RateConv = __OPLL_RateConv;
extern "C" {
    pub fn OPLL_RateConv_new(
        f_inp: f64,
        f_out: f64,
        ch: ::std::os::raw::c_int,
    ) -> *mut OPLL_RateConv;
}
extern "C" {
    pub fn OPLL_RateConv_reset(conv: *mut OPLL_RateConv);
}
extern "C" {
    pub fn OPLL_RateConv_putData(conv: *mut OPLL_RateConv, ch: ::std::os::raw::c_int, data: i16);
}
extern "C" {
    pub fn OPLL_RateConv_getData(conv: *mut OPLL_RateConv, ch: ::std::os::raw::c_int) -> i16;
}
extern "C" {
    pub fn OPLL_RateConv_delete(conv: *mut OPLL_RateConv);
}
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct __OPLL {
    pub clk: u32,
    pub rate: u32,
    pub chip_type: u8,
    pub adr: u32,
    pub inp_step: f64,
    pub out_step: f64,
    pub out_time: f64,
    pub reg: [u8; 64usize],
    pub test_flag: u8,
    pub slot_key_status: u32,
    pub rhythm_mode: u8,
    pub eg_counter: u32,
    pub pm_phase: u32,
    pub am_phase: i32,
    pub lfo_am: u8,
    pub noise: u32,
    pub short_noise: u8,
    pub patch_number: [i32; 9usize],
    pub slot: [OPLL_SLOT; 18usize],
    pub patch: [OPLL_PATCH; 38usize],
    pub pan: [u8; 16usize],
    pub pan_fine: [[f32; 2usize]; 16usize],
    pub mask: u32,
    pub ch_out: [i16; 14usize],
    pub mix_out: [i16; 2usize],
    pub conv: *mut OPLL_RateConv,
}
#[test]
fn bindgen_test_layout___OPLL() {
    const UNINIT: ::std::mem::MaybeUninit<__OPLL> = ::std::mem::MaybeUninit::uninit();
    let ptr = UNINIT.as_ptr();
    assert_eq!(
        ::std::mem::size_of::<__OPLL>(),
        3640usize,
        concat!("Size of: ", stringify!(__OPLL))
    );
    assert_eq!(
        ::std::mem::align_of::<__OPLL>(),
        8usize,
        concat!("Alignment of ", stringify!(__OPLL))
    );
    assert_eq!(
        unsafe { ::std::ptr::addr_of!((*ptr).clk) as usize - ptr as usize },
        0usize,
        concat!(
            "Offset of field: ",
            stringify!(__OPLL),
            "::",
            stringify!(clk)
        )
    );
    assert_eq!(
        unsafe { ::std::ptr::addr_of!((*ptr).rate) as usize - ptr as usize },
        4usize,
        concat!(
            "Offset of field: ",
            stringify!(__OPLL),
            "::",
            stringify!(rate)
        )
    );
    assert_eq!(
        unsafe { ::std::ptr::addr_of!((*ptr).chip_type) as usize - ptr as usize },
        8usize,
        concat!(
            "Offset of field: ",
            stringify!(__OPLL),
            "::",
            stringify!(chip_type)
        )
    );
    assert_eq!(
        unsafe { ::std::ptr::addr_of!((*ptr).adr) as usize - ptr as usize },
        12usize,
        concat!(
            "Offset of field: ",
            stringify!(__OPLL),
            "::",
            stringify!(adr)
        )
    );
    assert_eq!(
        unsafe { ::std::ptr::addr_of!((*ptr).inp_step) as usize - ptr as usize },
        16usize,
        concat!(
            "Offset of field: ",
            stringify!(__OPLL),
            "::",
            stringify!(inp_step)
        )
    );
    assert_eq!(
        unsafe { ::std::ptr::addr_of!((*ptr).out_step) as usize - ptr as usize },
        24usize,
        concat!(
            "Offset of field: ",
            stringify!(__OPLL),
            "::",
            stringify!(out_step)
        )
    );
    assert_eq!(
        unsafe { ::std::ptr::addr_of!((*ptr).out_time) as usize - ptr as usize },
        32usize,
        concat!(
            "Offset of field: ",
            stringify!(__OPLL),
            "::",
            stringify!(out_time)
        )
    );
    assert_eq!(
        unsafe { ::std::ptr::addr_of!((*ptr).reg) as usize - ptr as usize },
        40usize,
        concat!(
            "Offset of field: ",
            stringify!(__OPLL),
            "::",
            stringify!(reg)
        )
    );
    assert_eq!(
        unsafe { ::std::ptr::addr_of!((*ptr).test_flag) as usize - ptr as usize },
        104usize,
        concat!(
            "Offset of field: ",
            stringify!(__OPLL),
            "::",
            stringify!(test_flag)
        )
    );
    assert_eq!(
        unsafe { ::std::ptr::addr_of!((*ptr).slot_key_status) as usize - ptr as usize },
        108usize,
        concat!(
            "Offset of field: ",
            stringify!(__OPLL),
            "::",
            stringify!(slot_key_status)
        )
    );
    assert_eq!(
        unsafe { ::std::ptr::addr_of!((*ptr).rhythm_mode) as usize - ptr as usize },
        112usize,
        concat!(
            "Offset of field: ",
            stringify!(__OPLL),
            "::",
            stringify!(rhythm_mode)
        )
    );
    assert_eq!(
        unsafe { ::std::ptr::addr_of!((*ptr).eg_counter) as usize - ptr as usize },
        116usize,
        concat!(
            "Offset of field: ",
            stringify!(__OPLL),
            "::",
            stringify!(eg_counter)
        )
    );
    assert_eq!(
        unsafe { ::std::ptr::addr_of!((*ptr).pm_phase) as usize - ptr as usize },
        120usize,
        concat!(
            "Offset of field: ",
            stringify!(__OPLL),
            "::",
            stringify!(pm_phase)
        )
    );
    assert_eq!(
        unsafe { ::std::ptr::addr_of!((*ptr).am_phase) as usize - ptr as usize },
        124usize,
        concat!(
            "Offset of field: ",
            stringify!(__OPLL),
            "::",
            stringify!(am_phase)
        )
    );
    assert_eq!(
        unsafe { ::std::ptr::addr_of!((*ptr).lfo_am) as usize - ptr as usize },
        128usize,
        concat!(
            "Offset of field: ",
            stringify!(__OPLL),
            "::",
            stringify!(lfo_am)
        )
    );
    assert_eq!(
        unsafe { ::std::ptr::addr_of!((*ptr).noise) as usize - ptr as usize },
        132usize,
        concat!(
            "Offset of field: ",
            stringify!(__OPLL),
            "::",
            stringify!(noise)
        )
    );
    assert_eq!(
        unsafe { ::std::ptr::addr_of!((*ptr).short_noise) as usize - ptr as usize },
        136usize,
        concat!(
            "Offset of field: ",
            stringify!(__OPLL),
            "::",
            stringify!(short_noise)
        )
    );
    assert_eq!(
        unsafe { ::std::ptr::addr_of!((*ptr).patch_number) as usize - ptr as usize },
        140usize,
        concat!(
            "Offset of field: ",
            stringify!(__OPLL),
            "::",
            stringify!(patch_number)
        )
    );
    assert_eq!(
        unsafe { ::std::ptr::addr_of!((*ptr).slot) as usize - ptr as usize },
        176usize,
        concat!(
            "Offset of field: ",
            stringify!(__OPLL),
            "::",
            stringify!(slot)
        )
    );
    assert_eq!(
        unsafe { ::std::ptr::addr_of!((*ptr).patch) as usize - ptr as usize },
        1472usize,
        concat!(
            "Offset of field: ",
            stringify!(__OPLL),
            "::",
            stringify!(patch)
        )
    );
    assert_eq!(
        unsafe { ::std::ptr::addr_of!((*ptr).pan) as usize - ptr as usize },
        3448usize,
        concat!(
            "Offset of field: ",
            stringify!(__OPLL),
            "::",
            stringify!(pan)
        )
    );
    assert_eq!(
        unsafe { ::std::ptr::addr_of!((*ptr).pan_fine) as usize - ptr as usize },
        3464usize,
        concat!(
            "Offset of field: ",
            stringify!(__OPLL),
            "::",
            stringify!(pan_fine)
        )
    );
    assert_eq!(
        unsafe { ::std::ptr::addr_of!((*ptr).mask) as usize - ptr as usize },
        3592usize,
        concat!(
            "Offset of field: ",
            stringify!(__OPLL),
            "::",
            stringify!(mask)
        )
    );
    assert_eq!(
        unsafe { ::std::ptr::addr_of!((*ptr).ch_out) as usize - ptr as usize },
        3596usize,
        concat!(
            "Offset of field: ",
            stringify!(__OPLL),
            "::",
            stringify!(ch_out)
        )
    );
    assert_eq!(
        unsafe { ::std::ptr::addr_of!((*ptr).mix_out) as usize - ptr as usize },
        3624usize,
        concat!(
            "Offset of field: ",
            stringify!(__OPLL),
            "::",
            stringify!(mix_out)
        )
    );
    assert_eq!(
        unsafe { ::std::ptr::addr_of!((*ptr).conv) as usize - ptr as usize },
        3632usize,
        concat!(
            "Offset of field: ",
            stringify!(__OPLL),
            "::",
            stringify!(conv)
        )
    );
}
pub type OPLL = __OPLL;
extern "C" {
    pub fn OPLL_new(clk: u32, rate: u32) -> *mut OPLL;
}
extern "C" {
    pub fn OPLL_delete(arg1: *mut OPLL);
}
extern "C" {
    pub fn OPLL_reset(arg1: *mut OPLL);
}
extern "C" {
    pub fn OPLL_resetPatch(arg1: *mut OPLL, arg2: u8);
}
extern "C" {
    #[doc = " Set output wave sampling rate.\n @param rate sampling rate. If clock / 72 (typically 49716 or 49715 at 3.58MHz) is set, the internal rate converter is\n disabled."]
    pub fn OPLL_setRate(opll: *mut OPLL, rate: u32);
}
extern "C" {
    #[doc = " Set internal calcuration quality. Currently no effects, just for compatibility.\n >= v1.0.0 always synthesizes internal output at clock/72 Hz."]
    pub fn OPLL_setQuality(opll: *mut OPLL, q: u8);
}
extern "C" {
    #[doc = " Set pan pot (extra function - not YM2413 chip feature)\n @param ch 0..8:tone 9:bd 10:hh 11:sd 12:tom 13:cym 14,15:reserved\n @param pan 0:mute 1:right 2:left 3:center\n ```\n pan: 76543210\n            |+- bit 1: enable Left output\n            +-- bit 0: enable Right output\n ```"]
    pub fn OPLL_setPan(opll: *mut OPLL, ch: u32, pan: u8);
}
extern "C" {
    #[doc = " Set fine-grained panning\n @param ch 0..8:tone 9:bd 10:hh 11:sd 12:tom 13:cym 14,15:reserved\n @param pan output strength of left/right channel.\n            pan[0]: left, pan[1]: right. pan[0]=pan[1]=1.0f for center."]
    pub fn OPLL_setPanFine(opll: *mut OPLL, ch: u32, pan: *mut f32);
}
extern "C" {
    #[doc = " Set chip type. If vrc7 is selected, r#14 is ignored.\n This method not change the current ROM patch set.\n To change ROM patch set, use OPLL_resetPatch.\n @param type 0:YM2413 1:VRC7"]
    pub fn OPLL_setChipType(opll: *mut OPLL, type_: u8);
}
extern "C" {
    pub fn OPLL_writeIO(opll: *mut OPLL, reg: u32, val: u8);
}
extern "C" {
    pub fn OPLL_writeReg(opll: *mut OPLL, reg: u32, val: u8);
}
extern "C" {
    #[doc = " Calculate one sample"]
    pub fn OPLL_calc(opll: *mut OPLL) -> i16;
}
extern "C" {
    #[doc = " Calulate stereo sample"]
    pub fn OPLL_calcStereo(opll: *mut OPLL, out: *mut i32);
}
extern "C" {
    pub fn OPLL_setPatch(arg1: *mut OPLL, dump: *const u8);
}
extern "C" {
    pub fn OPLL_copyPatch(arg1: *mut OPLL, arg2: i32, arg3: *mut OPLL_PATCH);
}
extern "C" {
    #[doc = " Force to refresh.\n External program should call this function after updating patch parameters."]
    pub fn OPLL_forceRefresh(arg1: *mut OPLL);
}
extern "C" {
    pub fn OPLL_dumpToPatch(dump: *const u8, patch: *mut OPLL_PATCH);
}
extern "C" {
    pub fn OPLL_patchToDump(patch: *const OPLL_PATCH, dump: *mut u8);
}
extern "C" {
    pub fn OPLL_getDefaultPatch(type_: i32, num: i32, arg1: *mut OPLL_PATCH);
}
extern "C" {
    #[doc = "  Set channel mask\n  @param mask mask flag: OPLL_MASK_* can be used.\n  - bit 0..8: mask for ch 1 to 9 (OPLL_MASK_CH(i))\n  - bit 9: mask for Hi-Hat (OPLL_MASK_HH)\n  - bit 10: mask for Top-Cym (OPLL_MASK_CYM)\n  - bit 11: mask for Tom (OPLL_MASK_TOM)\n  - bit 12: mask for Snare Drum (OPLL_MASK_SD)\n  - bit 13: mask for Bass Drum (OPLL_MASK_BD)"]
    pub fn OPLL_setMask(arg1: *mut OPLL, mask: u32) -> u32;
}
extern "C" {
    #[doc = " Toggler channel mask flag"]
    pub fn OPLL_toggleMask(arg1: *mut OPLL, mask: u32) -> u32;
}
